version: '3'
services:
  server-1:
    container_name: server-1
    image: linuxkit/sshd:v1.0.0
    networks:
      ansible:
        ipv4_address: 172.20.0.2
    volumes:
      - type: bind
        source: ./ssh-conf
        target: /etc/ssh
    command: sh /etc/ssh/init-server.sh
  server-2:
    container_name: server-2
    image: linuxkit/sshd:v1.0.0
    networks:
      ansible:
        ipv4_address: 172.20.0.3
    volumes:
      - type: bind
        source: ./ssh-conf
        target: /etc/ssh
    command: sh /etc/ssh/init-server.sh

    
  server-3:
    container_name: server-3
    image: linuxkit/sshd:v1.0.0
    networks:
      ansible:
        ipv4_address: 172.20.0.4
    volumes:
      - type: bind
        source: ./ssh-conf
        target: /etc/ssh
    command: sh /etc/ssh/init-server.sh

networks:
  ansible:
    name: ansible
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1